version: '1'

services:
  quickmartServer:
    image: quickmartServer
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_PORT=3000
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
